sudo: required 
services: 
 - docker
before_install: 
 - docker build -t anisdhiyaeddine/react -f Dockerfile.dev .
script: 
 - docker run -e CI=true anisdhiyaeddine/react yarn test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-eu-west-3-769641087123"
  bucket_path: "react"
  on: 
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
   secure: "$AWS_SECRET_KEY"